INSERT INTO leagues (name, country_id) VALUES ('Turkish Basketball League (TBL)', 1);
INSERT INTO leagues (name, country_id) VALUES ('Turkish Basketball Second League (TB2L)', 1);
INSERT INTO leagues (name, country_id) VALUES ('Turkish Basketball Third League (TB3L)', 1);
INSERT INTO leagues (name, country_id) VALUES ('National Basketball Association (NBA)', 2);
INSERT INTO leagues (name, country_id) VALUES ('NBA Development League (NBADL)', 2);
INSERT INTO leagues (name, country_id) VALUES ('American Basketball Association (ABA)', 2);
INSERT INTO leagues (name, country_id) VALUES ('American Basketball League (ABL)', 2);
INSERT INTO leagues (name, country_id) VALUES ('American Professional Basketball League (APBL)', 2);
INSERT INTO leagues (name, country_id) VALUES ('Central Basketball Association (CBA)', 2);
INSERT INTO leagues (name, country_id) VALUES ('Basketball Bundesliga (BBL)', 3);
INSERT INTO leagues (name, country_id) VALUES ('2. Basketball Bundesliga (Pro A)', 3);
INSERT INTO leagues (name, country_id) VALUES ('British Basketball League (BBL)', 4);
INSERT INTO leagues (name, country_id) VALUES ('Ukrainian Basketball Superleague', 5);
INSERT INTO leagues (name, country_id) VALUES ('National Basketball League (NBL)', 6);
INSERT INTO leagues (name, country_id) VALUES ('Big V', 6);
